Add logs for debugging service

diff --git a/scripts/tests/api_compare/docker-compose.yml b/scripts/tests/api_compare/docker-compose.yml
--- a/scripts/tests/api_compare/docker-compose.yml
+++ b/scripts/tests/api_compare/docker-compose.yml
@@ -74,12 +74,16 @@ services:
     user: 0:0
     command:
       - |
-        set -uo pipefail        
+        set -uo pipefail
+        type curl >/dev/null 2>&1 || { echo >&2 "curl is required but it's not installed."; exit 1; }
+        curl -V
+
         echo "Waiting till Forest is ready"
         curl -s "http://forest:${FOREST_HEALTHZ_RPC_PORT}/readyz?verbose"
 
         retries=120
         for i in $(seq 1 $retries); do
+            echo "$i"
             if [[ "$(curl -s -o /dev/null -w '%{http_code}' http://forest:${FOREST_HEALTHZ_RPC_PORT}/readyz)" == "200" ]]; then
                 echo "Forest is ready"
                 break
