Run wallet and mpool tool test on devnet (#7263)

diff --git a/.github/workflows/forest.yml b/.github/workflows/forest.yml
--- a/.github/workflows/forest.yml
+++ b/.github/workflows/forest.yml
@@ -225,7 +225,14 @@ jobs:
       - name: Migration Regression Tests
         run: ./scripts/tests/calibnet_migration_regression_tests.sh
         timeout-minutes: ${{ fromJSON(env.SCRIPT_TIMEOUT_MINUTES) }}
+  calibnet-wallet-check-no-ops:
+    name: Wallet tests
+    runs-on: ubuntu-slim
+    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Wallet') }}
+    steps:
+      - run: echo "No-op job to trigger the required wallet tests."
   calibnet-wallet-check:
+    if: ${{ contains(github.event.pull_request.labels.*.name, 'Wallet') }}
     needs:
       - build-ubuntu
     name: Wallet tests
@@ -480,6 +487,18 @@ jobs:
       - name: Devnet check
         run: ./scripts/devnet/check.sh
         timeout-minutes: ${{ fromJSON(env.SCRIPT_TIMEOUT_MINUTES) }}
+      - name: Add forest binaries to PATH
+        run: |
+          chmod +x "$GITHUB_WORKSPACE"/forest*
+          echo "$GITHUB_WORKSPACE" >> "$GITHUB_PATH"
+      - name: Devnet wallet tests
+        run: |
+          set -euo pipefail
+          source ./scripts/devnet/wallet_harness.sh
+          devnet_wallet_env_init
+          forest-dev tests mpool
+          forest-dev tests wallet
+        timeout-minutes: ${{ fromJSON(env.SCRIPT_TIMEOUT_MINUTES) }}
       - name: Dump docker logs
         if: always()
         uses: jwalton/gh-docker-logs@v2
@@ -574,7 +593,6 @@ jobs:
       - calibnet-stateless-mode-check
       - calibnet-stateless-rpc-check
       - state-migrations-check
-      - calibnet-wallet-check
       - calibnet-no-discovery-checks
       - calibnet-kademlia-checks
       - calibnet-eth-mapping-check
